server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
#  instance:
#    hostname: 127.0.0.1
  client:
#    # false 表示不向注册中心注册自己
    register-with-eureka: true
    # false 表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #单机就是自己
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7001/eureka/
      #集群指向其他eureka 设置与 Eureka Service 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

feign:
  hystrix:
    enabled: true

