server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到 zookeeper 地址
    zookeeper:
      # 192.168.147.1  本机 ip 地址
      connect-string: 192.168.147.1:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3308/db_springcloud_guigu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456